@echo off
:loop
echo hahahahaahahahahahahahaahhahhahhahahhahahhahhaahhaahahahahahahahhahaahahahahahhaahhahhahaahhahahaaahahhahh!
echo hahahahaahahahahahahahaahhahhahhahahhahahhahhaahhaahahahahahahhaahhahhahaahhahahaaahahhahh!
echo hahahahaahahahahahahahaahhahhahhahahhahahhahhaahhahahh!
echo hahahahaahahahahahahahaahhahhahhahahhahahhahhaahhaahahahahaahahahahaahahhhaahhahhahaahhahahaaahahhahh!
goto loop
setup.bat